// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/osamikoyo/math-angel/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Cash is an autogenerated mock type for the Cash type
type Cash struct {
	mock.Mock
}

// GetTask provides a mock function with given fields: ctx, key
func (_m *Cash) GetTask(ctx context.Context, key string) (*model.Task, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Task, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Task); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTasks provides a mock function with given fields: ctx, key
func (_m *Cash) GetTasks(ctx context.Context, key string) ([]model.Task, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Task, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Task); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetTask provides a mock function with given fields: ctx, key, task
func (_m *Cash) SetTask(ctx context.Context, key string, task *model.Task) error {
	ret := _m.Called(ctx, key, task)

	if len(ret) == 0 {
		panic("no return value specified for SetTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *model.Task) error); ok {
		r0 = rf(ctx, key, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetTasks provides a mock function with given fields: ctx, key, tasks
func (_m *Cash) SetTasks(ctx context.Context, key string, tasks []model.Task) error {
	ret := _m.Called(ctx, key, tasks)

	if len(ret) == 0 {
		panic("no return value specified for SetTasks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []model.Task) error); ok {
		r0 = rf(ctx, key, tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCash creates a new instance of Cash. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCash(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cash {
	mock := &Cash{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
